### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by swlong** [scwatts/hicap#1]
Apologies for the screenshot. I'm running hicap on a large set of H. flu assemblies in parallel and noticed the following error, seemingly in find_proximal_fragments of locus.py: 

![hicap-screenshot](https://user-images.githubusercontent.com/2158927/58989907-6cbc9880-87aa-11e9-8ef2-8f972ff846e1.JPG)

Unfortunately, I can't determine how to trace this back to the particular sample that generated the error, until they're all finished and I search through looking for those that haven't generated output.  

Any insight is appreciated.

**Comment by scwatts** [comment]
I can see the likely cause of the issue in the hicap codebase but testing a fix would be difficult without an assembly that triggers this error state.

Having the the assembly (or region containing the capsule locus) would be very helpful in catching this corner case - one way to determine the identity of the problem assembly would be to capture stderr/stdout from the parallelised processes, for example:
```bash
mkdir -p output/ logs/
parallel 'hicap --query_fp {} --output_dir output/ 1>logs/{/.}.log 2>&1' ::: example/*fasta
```

You could then search the log files to identify the assembly of interest:
```bash
grep -rl 'AttributeError' logs/
```

With the assembly I'll be able to confirm the problematic code block, apply a fix, and push the change to github.

**Comment by swlong** [comment]
I've captured the log from an offending assembly and sent it to your email in your github profile. Appreciate the help.

**Comment by scwatts** [comment]
Thank you, the assembly was instrumental in fixing this bug! I've pushed the fix and created a new release. You'll need to use the latest commit on master or download v1.0.1 to use the fixed version of hicap.

**Comment by scwatts** [comment]
I've now updated the hicap bioconda recipe so you also have the option to install the latest release using conda
