### ISSUE TITLE
No result feedback

### ISSUE THREAD

**Issue by douco-ai** [scwatts/hicap#8]
Dear Author,
I hope this message finds you well.
I want to use hicap to predict serotypes, but there is no feedback after running it. The output folder is empty. How should I explain this? Here is the code:
hicap --query_fp 461_js.fasta --output_dir output/

18/07/2024 10:23:11 INFO: Checking dependencies
18/07/2024 10:23:11 INFO: Collecting ORFs from input assembly
18/07/2024 10:23:13 INFO: Searching for ORF hits in database
18/07/2024 10:23:43 INFO: Finding complete ORF hits
18/07/2024 10:23:43 INFO: No hits to any cap locus gene found, exiting

**Comment by scwatts** [comment]
Hi @douco-ai, thanks for opening the issue. This is the expected behaviour for hicap - there was no high-quality evidence for cap locus genes detected in your assembly so no outputs were available to be written to disk.
